name: pose_detection_example
description: Example app for pose_detection
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.2.1
  file_selector: ^1.1.0
  file_selector_macos: ^0.9.5
  pose_detection:
    path: ../
  flutter_colorpicker: ^1.1.0
  path_provider: ^2.1.5
  camera: ^0.12.0
  camera_macos: ^0.0.9
  opencv_dart: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/samples/
