name: pose_detection
description: Pose & landmark detection using on-device TFLite models.
version: 1.0.3

repository: https://github.com/hugocornellier/pose_detection
homepage: https://github.com/hugocornellier/pose_detection

topics:
  - tflite
  - pose-detection
  - computer-vision
  - flutter-plugin

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_litert: ^1.0.1
  opencv_dart: ^2.1.0
  meta: ^1.17.0
  web: ^1.1.1
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/models/pose_detection.tflite
    - assets/models/pose_landmark_lite.tflite
    - assets/models/pose_landmark_full.tflite
    - assets/models/pose_landmark_heavy.tflite
    - assets/models/yolov8n_float32.tflite
    - assets/samples/multi1.jpg
    - assets/samples/pose1.jpg
    - assets/samples/pose2.jpg
    - assets/samples/pose3.jpg
    - assets/samples/pose4.jpg
    - assets/samples/pose5.jpg
    - assets/samples/pose6.jpg
    - assets/samples/pose7.jpg

  plugin:
    platforms:
      ios:
        dartPluginClass: PoseDetectionDart
      android:
        dartPluginClass: PoseDetectionDart
      macos:
        pluginClass: PoseDetectionPlugin
      windows:
        pluginClass: PoseDetectionPlugin
      linux:
        pluginClass: PoseDetectionPlugin
      web:
        pluginClass: PoseDetectionWeb
        fileName: pose_detection_web.dart
