name: pose_detection_example_web
description: Web example for pose_detection
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  pose_detection:
    path: ../
  web: ^1.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/samples/
